---
# Tests bash script on macOS

name: macOS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:


jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Test script
        run: |
          chmod +x macos.sh
          sudo bash macos.sh
